spring.application.name=mcp-git-tool

spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.name=git-tool-mcp-server
spring.ai.mcp.server.version=1.0.0

spring.main.web-application-type=none

spring.main.banner-mode=off
logging.pattern.console=

logging.file.name=/Users/vishal_pansare/Kyros_Github/MCP_Git_Tools/mcp-server.log

git.pat=

github.api.base.url=https://api.github.com
# e.g., https://github.company.com/api/v3).
